const adminPanelData = [
  {
    id: 1,
    icon: "icons/admin/RequestsAllListing.svg",
    title: "All Listing Requests",
    query: "All",
    route: "allListingRequest",
    details: "New Property Listing requests yet to be posted.",
  },
  {
    id: 2,
    icon: "icons/admin/RequestsSale.svg",
    title: "Sale Requests",
    query: "Sell",
    route: "allListingRequest",
    details: "All The properties for Sale that are now live on DreamFinder.",
  },
  {
    id: 3,
    icon: "icons/admin/RequestsRent.svg",
    title: "Rent Requests",
    query: "Rent",
    route: "allListingRequest",
    details: "All The properties for Rent that are now live on DreamFinder.",
  },
  {
    id: 4,
    icon: "icons/admin/RequestsAuction.svg",
    title: "Auction Requests",
    query: "Auction",
    route: "allListingRequest",
    details:
      "Everything related to auctions one place, according to your convenience.",
  },
  {
    id: 5,
    icon: "icons/admin/PostNewProperty.svg",
    title: "Post NEW Property",
    query: "All",
    route: "newPropertyListing",
    details: "New Property Listing requests yet to be posted.",
  },
  {
    id: 6,
    icon: "icons/admin/ListedAll.svg",
    title: "All Property Listings",
    query: "All",
    route: "postedProperties",
    details: "All The properties that are now live on DreamFinder",
  },
  {
    id: 7,
    icon: "icons/admin/ListedSale.svg",
    title: "Listed for Sale",
    query: "Sell",
    route: "postedProperties",
    details: "All The properties for Sale that are now live on DreamFinder.",
  },
  {
    id: 8,
    icon: "icons/admin/ListedRent.svg",
    title: "Listed for Rent",
    query: "Rent",
    route: "postedProperties",
    details: "All The properties for Rent that are now live on DreamFinder.",
  },
  {
    id: 9,
    icon: "icons/admin/ListedAuction.svg",
    title: "Listed for Auctions",
    query: "Auction",
    route: "postedProperties",
    details:
      "Everything related to auctions one place, according to your convenience.",
  },
  {
    id: 10,
    icon: "icons/admin/AreaGuides.svg",
    title: "Area Guides",
    query: "All",
    route: "allAreaGuides",
    details: "Create, Update, Remove and View all Area Guides",
  },
  {
    id: 11,
    icon: "icons/admin/BlogPosts.svg",
    title: "Blogs",
    query: "All",
    route: "allBlogPosts",
    details: "Search Filters you’ve saved for later queries.",
  },
  {
    id: 12,
    icon: "icons/admin/ManageAgents.svg",
    title: "Manage Agents",
    query: "All",
    route: "",
    details: "Manage payment for properties you’ve rented.",
  },

  {
    id: 13,
    icon: "icons/admin/Surveying.svg",
    title: "Surveying",
    query: "All",
    route: "",
    details: "Manage payment for properties you’ve rented.",
  },
  {
    id: 14,
    icon: "icons/admin/career.svg",
    title: "Careers & Jobs",
    query: "All",
    route: "allJobPosts",
    details: "Post Jobs and See Incoming Job Requests",
  },
  {
    id: 15,
    icon: "icons/admin/bank.svg",
    title: "Bank Loan Info",
    query: "All",
    route: "",
    details: "List of all users and managing options",
  },
  {
    id: 16,
    icon: "icons/admin/location.svg",
    title: "Popular Locations",
    query: "All",
    route: "postPopularLocations",
    details: "Post Jobs and See Incoming Job Requests",
  },
  {
    id: 17,
    icon: "icons/admin/Users.svg",
    title: "Users",
    query: "All",
    route: "allUsers",
    details: "List of all users and managing options",
  },
  {
    id: 18,
    icon: "icons/admin/ManageAdmins.svg",
    title: "Manage Admins",
    route: "",
    query: "All",
    details: "Manage Payments from renters of your property ",
  },
  {
    id: 19,
    icon: "icons/admin/SiteSettings.svg",
    title: "Site Settings",
    route: "",
    query: "All",
    details: "Change Site Settings an Preferences",
  },
  {
    id: 20,
    icon: "icons/admin/PostNewProperty.svg",
    title: "Collect New Property",
    route: "collectNewProperty",
    query: "All",
    details: "Change Site Settings an Preferences",
  },
  {
    id: 21,
    icon: "icons/admin/ListedAll.svg",
    title: "Collected Properties",
    route: "allCollectedProperties",
    query: "All",
    details: "Change Site Settings an Preferences",
  },
];

export default adminPanelData;
