const adminPanelData = [
  {
    id: 1,
    icon: "icons/admin/RequestsAllListing.svg",
    title: "All Listing Requests",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 2,
    icon: "icons/admin/RequestsSale.svg",
    title: "Sale Requests",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 3,
    icon: "icons/admin/RequestsRent.svg",
    title: "Rent Requests",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 4,
    icon: "icons/admin/RequestsAuction.svg",
    title: "Auction Requests",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 5,
    icon: "icons/admin/PostNewProperty.svg",
    title: "Post NEW Property",
    route: "newPropertyListing",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 6,
    icon: "icons/admin/ListedAll.svg",
    title: "All Property Listings",
    route: "postedProperties",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 7,
    icon: "icons/admin/ListedSale.svg",
    title: "Listed for Sale",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 8,
    icon: "icons/admin/ListedRent.svg",
    title: "Listed for Rent",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 9,
    icon: "icons/admin/ListedAuction.svg",
    title: "Listed for Auctions",
    route: "allListingRequest",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 10,
    icon: "icons/admin/AreaGuides.svg",
    title: "Area Guides",
    route: "allAreaGuides",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 11,
    icon: "icons/admin/BlogPosts.svg",
    title: "Blogs",
    route: "allBlogPosts",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 12,
    icon: "icons/admin/ManageAgents.svg",
    title: "Manage Agents",
    route: "",
    details: "Post a new Property to Rent, Sell or Auction.",
  },

  {
    id: 13,
    icon: "icons/admin/Surveying.svg",
    title: "Surveying",
    route: "",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 14,
    icon: "icons/admin/Users.svg",
    title: "Users",
    route: "profile",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 15,
    icon: "icons/admin/ManageAdmins.svg",
    title: "Manage Admins",
    route: "",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
  {
    id: 16,
    icon: "icons/admin/SiteSettings.svg",
    title: "Site Settings",
    route: "",
    details: "Post a new Property to Rent, Sell or Auction.",
  },
];

export default adminPanelData;
